require: rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - lib/**/*.rb

  Exclude:
    - script/**/*
    - spec/**/*

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/jekyll/page-without-a-file.rb
